version: '3.7'
services:
  jenkins:
    build:
      context: ./
    privileged: true
    user: 1000:1000
    ports:
      - 8180:8080
      - 50000:50000
    container_name: jenkins
    restart: always
    tty: true
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home

  tomcat:
    image: tomcat:9.0-slim
    ports:
      - 8181:8181
    user: 1000:1000
    container_name: tomcat
    volumes:
      - ./tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./tomcat/conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./tomcat/webapps/:/usr/local/tomcat/webapps/