@startuml
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User
participant CalculatorApp
participant Calculator

create Calculator
CalculatorApp -> Calculator : new
Calculator -> Calculator : accumulator=0.0

User ->> CalculatorApp : "add 6"
CalculatorApp ->> Calculator : doOperation("add", 6)
User ->> CalculatorApp : "factorial"
CalculatorApp ->> Calculator : doOperation("factorial", 0)
CalculatorApp <<-- Calculator : returns 6
User <<-- CalculatorApp : displays "6"

Calculator -> Calculator : accumulator=720.0
CalculatorApp <<-- Calculator : returns 720.0
User <<-- CalculatorApp : displays "720.0"

User ->> CalculatorApp : "third"
CalculatorApp ->> Calculator : doOperation("third")
Calculator -> Calculator : accumulator=240
CalculatorApp <<-- Calculator : returns 240.0
User <<-- CalculatorApp : displays "240.0"
@enduml